const {_electron}=require('playwright');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const assert=require('node:assert/strict');const {Store}=require('../src/core.cjs');
(async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'srm-health-ui-'));let app;const launch=()=>_electron.launch({args:['.'],cwd:path.resolve(__dirname,'..'),env:{...process.env,SRM_DATA_DIR:dir,SRM_DRIVER:'1'}});try{
 const store=new Store(dir);store.addProfile('Shop kiểm thử');store.data.settings.autoScan=false;store.save();app=await launch();let page=await app.firstWindow();await page.waitForFunction(()=>!!window.srm);
 await app.evaluate(async({app})=>{const {interfaceMonitor:m,store}=app.srmDriver,id=store.data.profiles[0].id;const observation={availability:'ready',issues:[],features:{search:{tag:'INPUT',display:'block'}},palette:{}};await m.record(id,'products','list',null,observation);await m.record(id,'products','list',null,{...observation,issues:['Thiếu cột <img src=x>'],features:{}});});
 await page.waitForFunction(()=>document.querySelector('#interface-health').classList.contains('changed'));await page.locator('nav [data-tab="settings"]').click();await page.locator('#interface-details summary').click();assert.equal(await page.locator('#interface-records img').count(),0);assert.equal(await page.locator('[data-interface-accept]').count(),0);
 await app.close();app=await launch();page=await app.firstWindow();await page.waitForFunction(()=>document.querySelector('#interface-health').classList.contains('changed'));await page.locator('nav [data-tab="settings"]').click();
 await app.evaluate(({app})=>{const {interfaceMonitor:m,store,scanner,products,integrations}=app.srmDriver;globalThis.sequence=[];const observation={availability:'ready',issues:[],features:{search:{tag:'INPUT',display:'flex'}},palette:{}};
 scanner.scan=async id=>{globalThis.sequence.push('returns');await m.record(id,'returns','list',null,{...observation,features:{heading:{tag:'DIV'}}});return {rows:[],totalOrders:0,ignored:0,unresolved:0};};products.scanner.open=async id=>{globalThis.sequence.push('products');await m.record(id,'products','list',null,observation);};integrations.drain=async()=>{globalThis.sequence.push('drain');};globalThis.fetch=async()=>({ok:true,text:async()=> 'Mã đơn hàng,Mã vận đơn\n260921TEST001,SPX111'});});
 const before=await page.evaluate(()=>window.srm.call('snapshot'));await page.locator('#interfaces-check').click();await page.waitForFunction(()=>!document.querySelector('#interfaces-check').disabled);let after=await page.evaluate(()=>window.srm.call('snapshot'));assert.equal(after.profiles[0].lastScan,before.profiles[0].lastScan,'Manual UI check does not ingest orders');assert.equal(after.interfaces.find(r=>r.module==='products').canAccept,true);
 await page.locator('#interface-details summary').click();
 for(const width of [1440,780,390]){await app.evaluate(({BrowserWindow},w)=>{const win=BrowserWindow.getAllWindows()[0];win.setMinimumSize(360,500);win.setSize(w,900);},width);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
 await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(1440,960));if(process.env.SRM_HEALTH_SCREENSHOT)await page.screenshot({path:process.env.SRM_HEALTH_SCREENSHOT});
 await app.evaluate(({dialog})=>{dialog.showMessageBox=async()=>({response:0});});await page.locator('[data-interface-accept]').click();assert.ok((await page.evaluate(()=>window.srm.call('snapshot'))).interfaces.some(r=>r.status==='changed'));
 await app.evaluate(({dialog})=>{dialog.showMessageBox=async()=>({response:1});});await page.locator('[data-interface-accept]').click();await page.waitForFunction(()=>document.querySelector('#interface-health').classList.contains('ok'));
 await app.evaluate(()=>{globalThis.sequence=[];});await page.evaluate(()=>window.srm.call('scan'));const sequence=await app.evaluate(()=>globalThis.sequence);assert.ok(sequence.indexOf('returns')<sequence.indexOf('products'));assert.ok(sequence.indexOf('drain')<sequence.indexOf('products'),'Fresh return delivery precedes extra product health probe');assert.equal((await page.evaluate(()=>window.srm.call('snapshot'))).interfaces.length,2);
 await assert.rejects(page.evaluate(()=>window.srm.call('interfaces-report','../../credentials.enc')),/Chưa có báo cáo/);
 console.log('PASS interface UI: red alert persists restart, escaped reports, explicit acceptance, readonly manual checks, automatic second-module probes, responsive layouts and confined evidence opening.');
}finally{if(app)await app.close();fs.rmSync(dir,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exitCode=1;});
