const {_electron}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const os=require('node:os');const {Store}=require('../src/core.cjs');
(async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'srm-products-ui-'));let app;try{
 const s=new Store(dir),profile=s.addProfile('Shop test');s.data.settings.autoScan=false;s.save();
 app=await _electron.launch({args:['.'],cwd:path.resolve(__dirname,'..'),env:{...process.env,SRM_DATA_DIR:dir,SRM_DRIVER:'1'}});const page=await app.firstWindow();await page.waitForFunction(()=>!!window.srm);const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await app.evaluate(({app})=>{const {products:p,store}=app.srmDriver;p.load=async()=>{p.ingest(store.data.profiles[0].id,{shop:'shop',total:1,pages:1,scannedAt:new Date().toISOString(),rows:[{productId:'123',modelId:'456',name:'Sản phẩm <img src=x>',variant:'Hộp',price:100000,stock:20}]});p.data.rows[0].sync='synced';};p.sync=async()=>{};p.scanner.edit=async(id,r,e,o)=>{if(e.value===999)throw Error('Giá trị đã thay đổi trên Shopee');o.beforeSubmit();return {row:{...r,[e.field]:e.value}};};});
 await page.locator('nav [data-tab="products"]').click();await page.locator('#products-load').click();await page.locator('[data-product]').first().waitFor();assert.equal(await page.locator('#product-rows img').count(),0);
 await page.locator('button[data-field="price"]').click();await page.locator('#product-value').fill('120000');await page.locator('#product-edit-cancel').click();assert.equal((await page.evaluate(()=>window.srm.call('snapshot'))).products.actions.length,0);
 await page.locator('button[data-field="stock"]').click();await page.locator('#product-value').fill('0');await page.locator('#product-edit-save').click();await page.waitForFunction(()=>!document.querySelector('#product-dialog').open);assert.equal((await page.evaluate(()=>window.srm.call('snapshot'))).products.rows[0].stock,0);
 await page.locator('button[data-field="price"]').click();await page.locator('#product-value').fill('999');await page.locator('#product-edit-save').click();await page.waitForFunction(()=>document.querySelector('#product-edit-error').textContent.includes('đã thay đổi'));assert.equal(await page.locator('#product-value').inputValue(),'999');await page.locator('#product-edit-cancel').click();
 await page.locator('button[data-field="price"]').click();await page.locator('#product-value').fill('120000');await page.locator('#product-edit-save').click();await page.waitForFunction(()=>!document.querySelector('#product-dialog').open);assert.equal((await page.evaluate(()=>window.srm.call('snapshot'))).products.rows[0].price,120000);
 for(const width of [1440,780,390]){await app.evaluate(({BrowserWindow},w)=>{const win=BrowserWindow.getAllWindows()[0];win.setMinimumSize(360,500);win.setSize(w,900);},width);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.locator('button[data-field="price"]').click();assert.ok(await page.evaluate(()=>{const r=document.querySelector('#product-dialog').getBoundingClientRect();return r.left>=0&&r.right<=innerWidth;}));await page.locator('#product-edit-cancel').click();}
 await page.evaluate(()=>window.srm.call('settings',{autoScan:true,intervalMinutes:1,notionEnabled:false,telegramEnabled:false}));
 const due=(await page.evaluate(()=>window.srm.call('snapshot'))).nextScan;
 await app.evaluate(({app})=>{globalThis.returnCalls=0;globalThis.originalNow=Date.now;app.srmDriver.products.load=()=>new Promise(resolve=>globalThis.finishProduct=resolve);app.srmDriver.scanner.scan=async()=>{globalThis.returnCalls++;Date.now=globalThis.originalNow;return {rows:[],totalOrders:0,ignored:0,unresolved:0};};globalThis.fetch=async()=>({ok:true,text:async()=> 'Mã đơn hàng,Mã vận đơn\n260901TEST001,SPX123'});});
 const held=page.evaluate(()=>window.srm.call('products-load'));await page.waitForFunction(async()=> (await window.srm.call('snapshot')).products.busy);
 await app.evaluate(()=>{Date.now=()=>globalThis.originalNow()+120000;});await page.waitForTimeout(5500);assert.equal(await app.evaluate(()=>globalThis.returnCalls),0,'Returns must not navigate during product operation');assert.equal((await page.evaluate(()=>window.srm.call('snapshot'))).nextScan,due,'Product operations preserve schedule');
 await assert.rejects(page.evaluate(()=>window.srm.call('scan')),/Sản phẩm/);await assert.rejects(page.evaluate(()=>window.srm.call('products-sync')),/bận/);
 await app.evaluate(()=>globalThis.finishProduct());await held;await page.waitForFunction(async()=>{const d=await window.srm.call('snapshot');return !d.scanning&&d.nextScan!==null;});assert.equal(await app.evaluate(()=>globalThis.returnCalls),1,'Overdue returns resumes immediately');assert.equal((await page.evaluate(()=>window.srm.call('snapshot'))).settings.intervalMinutes,1);
 assert.deepEqual(errors,[]);console.log('PASS products UI: load, cancel, price/zero stock save, failure, XSS, responsive dialogs, operation lock and overdue returns scheduler.');
}finally{if(app)await app.close();fs.rmSync(dir,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exitCode=1;});
