const {test}=require('node:test');const assert=require('node:assert/strict');const {chromium}=require('playwright');const {ProductScanner,readProducts}=require('../src/product-scanner.cjs');
const single=(id,price='₫100.000')=>'<tr class="eds-table__row"><td><div class="product-variation-item"><div class="item-id">ID Sản phẩm: '+id+'</div><a class="product-name-wrap">Sản phẩm '+id+'</a><div>Model ID: '+id+'9</div><div class="list-view-price">'+price+'</div><div class="stock-content"><span class="stock-text">20</span></div></div></td></tr>';
async function setup(t){const browser=await chromium.launch({channel:'chrome',headless:true});t.after(()=>browser.close());return browser.newPage();}
test('reads distinct variants, rejects price ranges and missing model instead of guessing',async t=>{
 const page=await setup(t);await page.setContent('<table>'+single('123')+'<tr><td><div class="product-variation-item"><div class="item-id">ID Sản phẩm: 456</div><a class="product-name-wrap">Multi</a></div>'+[1,2].map(n=>'<div class="model-list-item"><div class="variation-name-info-name">Loại '+n+'</div><div>Model ID: '+n+'111</div><div class="list-view-model-price">₫'+n+'00.000</div><span class="stock-text">'+n+'</span></div>').join('')+'</td></tr></table>');
 let d=await page.evaluate(readProducts);assert.equal(d.rows.length,3);assert.equal(d.rows[2].price,200000);assert.equal(d.rows[2].modelId,'2111');
 await page.setContent('<table>'+single('123','₫100.000 - ₫200.000')+'</table>');d=await page.evaluate(readProducts);assert.equal(d.rows.length,0);assert.equal(d.errors.length,1);
 await page.setContent('<span>2 Sản Phẩm gợi ý</span><p class="list-header-title">159 Sản Phẩm</p><table>'+single('123').replace('>20<','>Hết hàng<')+'</table>');d=await page.evaluate(readProducts);assert.equal(d.total,159);assert.equal(d.rows[0].stock,0);
});
test('selects 48, traverses all pages and verifies complete totals',async t=>{
 const page=await setup(t);await page.setContent('<div class="account-info"><span class="subaccount-name">shop</span></div><p class="list-header-title">2 Sản Phẩm</p><table><tbody>'+single('123')+'</tbody></table><div class="product-list-pagination"><span class="eds-pager__current">1</span><span class="eds-pager__total">2</span><span class="eds-pagination-sizes__content">12/trang</span><div class="eds-pagination-sizes__popper"><button class="eds-dropdown-item">48</button></div><button class="eds-pager__button-next">Next</button></div>');
 await page.evaluate(html=>{document.querySelector('.eds-dropdown-item').onclick=()=>document.querySelector('.eds-pagination-sizes__content').textContent='48/trang';document.querySelector('.eds-pager__button-next').onclick=()=>{document.querySelector('tbody').innerHTML=html;document.querySelector('.eds-pager__current').textContent='2';};},single('456'));
 const scanner=new ProductScanner({});scanner.open=async()=>page;const result=await scanner.scan('profile');assert.equal(result.total,2);assert.equal(result.rows.length,2);assert.equal(result.pages,2);
 await page.locator('.eds-pager__current').evaluate(e=>e.textContent='1');await page.locator('.eds-pager__total').evaluate(e=>e.textContent='1');await assert.rejects(scanner.scan('profile'),/Chưa đọc đủ/);
});
test('variant edit changes only the selected row; ambiguous labels block submit',async t=>{
 const page=await setup(t);await page.setContent('<div class="list-view-model-price">100</div><div class="eds-modal__content" hidden><h2>Cập nhật giá</h2><div class="price-edit-name">Multi</div><input placeholder="Batch"><table>'+['Small','Large'].map((s,i)=>'<tr class="eds-table__row"><td class="price-edit-variation">'+s+'</td><td><input value="'+(i?200:100)+'"></td></tr>').join('')+'</table><button>Hủy bỏ</button><button>Cập nhật giá</button></div>');
 await page.evaluate(()=>{window.saved=0;document.querySelector('.list-view-model-price').onclick=()=>document.querySelector('.eds-modal__content').hidden=false;document.querySelectorAll('button')[0].onclick=()=>document.querySelector('.eds-modal__content').hidden=true;document.querySelectorAll('button')[1].onclick=()=>{window.saved++;document.querySelector('.eds-modal__content').hidden=true;};});
 const scanner=new ProductScanner({}),target={shop:'shop',name:'Multi',variant:'Large',productId:'123',modelId:'456'};scanner.find=async()=>({page,unit:page.locator('body'),row:{...target,price:Number(await page.locator('tr input').nth(1).inputValue())}});
 const result=await scanner.edit('p',target,{field:'price',expected:200,value:250});assert.equal(result.row.price,250);assert.deepEqual(await page.locator('input').evaluateAll(es=>es.map(e=>e.value)),['','100','250']);assert.equal(await page.evaluate(()=>window.saved),1);
 await page.locator('.price-edit-variation').first().evaluate(e=>e.textContent='Large');await assert.rejects(scanner.edit('p',target,{field:'price',expected:250,value:300}),/duy nhất phân loại/);assert.equal(await page.evaluate(()=>window.saved),1);
});
test('edit checks identity/old value, saves once and verifies by fresh reread',async t=>{
 const page=await setup(t);await page.setContent('<table>'+single('123')+'</table><div class="eds-modal__content" hidden><h2>Cập nhật kho hàng</h2><p class="stock-edit-name">Sản phẩm 123</p><input value="20"><button>Hủy bỏ</button><button>Cập nhật</button></div>');
 await page.evaluate(()=>{window.saved=0;document.querySelector('.stock-content').onclick=()=>document.querySelector('.eds-modal__content').hidden=false;document.querySelectorAll('button')[0].onclick=()=>document.querySelector('.eds-modal__content').hidden=true;document.querySelectorAll('button')[1].onclick=()=>{window.saved++;document.querySelector('.stock-text').textContent=document.querySelector('input').value;document.querySelector('.eds-modal__content').hidden=true;};});
 const scanner=new ProductScanner({}),target={shop:'shop',name:'Sản phẩm 123',variant:'',productId:'123',modelId:'1239'};
 scanner.find=async()=>({page,row:(await page.evaluate(readProducts)).rows[0],unit:page.locator('.product-variation-item')});let submitted=0;
 const result=await scanner.edit('p',target,{field:'stock',expected:20,value:0},{beforeSubmit:()=>submitted++});assert.equal(result.row.stock,0);assert.equal(submitted,1);assert.equal(await page.evaluate(()=>window.saved),1);
 await assert.rejects(scanner.edit('p',target,{field:'stock',expected:20,value:1}),/đã thay đổi/);assert.equal(await page.evaluate(()=>window.saved),1);
 await page.locator('input').evaluate(e=>e.value='99');await assert.rejects(scanner.edit('p',target,{field:'stock',expected:0,value:1}),/hộp sửa khác/);assert.equal(await page.evaluate(()=>window.saved),1);
});
