const {_electron} = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const sharp = require('sharp');
const {Store} = require('../src/core.cjs');

(async () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'srm-studio-ui-'));
  let app;
  try {
    const store = new Store(dir); store.addProfile('Shop chính'); store.addProfile('Shop phụ'); store.data.settings.autoScan = false; store.save();
    const previewDataUrl = 'data:image/jpeg;base64,' + (await sharp({create: {width: 160, height: 160, channels: 3, background: '#d7eedf'}}).jpeg().toBuffer()).toString('base64');
    app = await _electron.launch({args: ['.'], cwd: path.resolve(__dirname, '..'), env: {...process.env, SRM_DATA_DIR: dir, SRM_DRIVER: '1'}});
    const page = await app.firstWindow(); await page.waitForFunction(() => !!window.srm && typeof renderStudio === 'function');
    const errors = []; page.on('pageerror', error => errors.push(error.message));
    await app.evaluate(({app}, {previewDataUrl, dir}) => {
      const {studio, products, store, replacements, replacementEditor, scanner, gemini, chatgpt, drive, integrations} = app.srmDriver;
      globalThis.studioCalls = {created: [], generated: [], approved: [], published: [], generatedRequests: [], images: [], attached: [], activated: [], run: [], scanned: [], loaded: 0, loadedProducts: 0, browserReads: 0, notionCreates: 0};
      const create = studio.create.bind(studio);
      studio.create = payload => {globalThis.studioCalls.created.push(payload); return create(payload);};
      for (const [index, profile] of store.data.profiles.entries()) products.ingest(profile.id, {shop: 'shop' + index, total: 1, pages: 1, scannedAt: new Date().toISOString(), rows: [
        {productId: String(123 + index), modelId: String(456 + index), name: (index ? 'Beta' : 'Alpha') + ' <img src=x>', variant: '', price: index ? 210000 : 100000, stock: 20},
        ...(!index ? [{productId: '123', modelId: '999', name: 'Alpha <img src=x>', variant: 'Gói', price: 100000, stock: 12}] : []),
      ]});
      const complete = job => {studio.save(); return studio.publicJob(job);};
      const generate = studio.generate.bind(studio), publish = studio.publish.bind(studio);
      studio.generate = async id => {globalThis.studioCalls.generated.push(id); return generate(id);};
      studio.approve = id => {globalThis.studioCalls.approved.push(id); throw Error('The removed approval action must not run');};
      studio.publish = async id => {globalThis.studioCalls.published.push(id); return publish(id);};
      const browserRead = async () => {globalThis.studioCalls.browserReads++; throw Error('Writing and publishing must not open Shopee');};
      replacementEditor.inspect = browserRead; replacementEditor.open = browserRead; scanner.context = browserRead;
      store.data.settings.replacementStudio.geminiModel = 'gemini-test-flash'; store.save();
      gemini.secrets = () => ({geminiApiKey: 'AQ.fake-key-only-in-isolated-test'});
      gemini.fetch = async (url, request) => {
        if (!url.endsWith('models/gemini-test-flash:generateContent')) throw Error('Unexpected Gemini API request');
        const body = JSON.parse(request.body), payload = JSON.parse(body.contents[0].parts[0].text);
        globalThis.studioCalls.generatedRequests.push(payload);
        return {ok: true, json: async () => ({candidates: [{finishReason: 'STOP', content: {parts: [{text: JSON.stringify({name: 'Tên đã viết <img src=x>', description: 'Mô tả dựa trên prompt và tên sản phẩm mới.\nNhân viên kiểm tra trước khi đăng.'})}]}}]})};
      };
      // Keep the real Studio publish/code/identity guards; replace only the remote Notion transport.
      const pages = new Map(), blocks = new Map(), databaseId = 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa';
      const database = {id: databaseId, properties: {}};
      studio.data.databaseId = databaseId;
      integrations.listPages = async id => [...pages.values()].filter(page => page.parent.database_id === id);
      integrations.notion = async (endpoint, method = 'GET', body) => {
        if (endpoint === 'databases/' + databaseId) {
          if (method === 'PATCH') for (const [name, definition] of Object.entries(body.properties)) database.properties[name] = {...definition, type: Object.keys(definition)[0]};
          return structuredClone(database);
        }
        if (endpoint === 'pages' && method === 'POST') {
          globalThis.studioCalls.notionCreates++;
          const id = globalThis.studioCalls.notionCreates.toString(16).padStart(32, 'b');
          const page = {id, url: 'https://app.notion.com/p/' + id, parent: body.parent, properties: body.properties};
          pages.set(id, structuredClone(page)); blocks.set(id, body.children.map((block, index) => ({...structuredClone(block), id: String(index + 1).padStart(32, 'c')})));
          if (globalThis.failAfterNotionCreate) {globalThis.failAfterNotionCreate = false; throw Error('Lost response after isolated Notion create');}
          return structuredClone(page);
        }
        if (endpoint.startsWith('pages/')) {const page = pages.get(endpoint.slice(6)); if (page) return structuredClone(page);}
        const children = /^blocks\/([^/]+)\/children/.exec(endpoint);
        if (children && blocks.has(children[1])) return {results: structuredClone(blocks.get(children[1])), has_more: false};
        throw Error('Unexpected fake Notion request: ' + method + ' ' + endpoint);
      };
      studio.images = async id => {
        const job = studio.get(id); globalThis.studioCalls.images.push(id);
        job.driveAssets = {images: Array.from({length: 5}, (_, index) => ({filename: index === 4 ? '<img src=x>.jpg' : String(index + 1) + '.jpg', bytes: 123456, width: 1024, height: 1024, previewDataUrl: index === 4 ? 'javascript:alert(1)' : previewDataUrl}))};
        job.localFolder = dir; job.status = 'images-ready'; return complete(job);
      };
      studio.attach = async id => {const job = studio.get(id); globalThis.studioCalls.attached.push(id); job.imagesReady = true; job.status = 'attached'; return complete(job);};
      studio.activate = async id => {const job = studio.get(id); globalThis.studioCalls.activated.push(id); return {rowId: job.rowId, url: job.notionUrl};};
      replacements.prepare = async (rowId, url) => {
        const row = products.data.rows.find(item => item.id === rowId);
        const plan = {id: 'studio-test-plan', rowId, target: {...row, name: row.name}, articleUrl: url, article: {product: {name: 'Tên mới', description: 'Mô tả mới'}}, schema: {fields: []}, diff: {changes: []}, images: [{filename: '1.jpg', previewDataUrl, bytes: 123456, width: 1024, height: 1024}], assets: {images: [{filename: '1.jpg', previewDataUrl, bytes: 123456, width: 1024, height: 1024}]}, status: 'prepared', createdAt: new Date().toISOString(), expiresAt: Date.now() + 600000};
        replacements.data.plans.unshift(plan); replacements.save(); return replacements.publicPlan(plan);
      };
      replacements.run = async id => {globalThis.studioCalls.run.push(id); return {};};
      products.sync = async () => {};
      products.load = async () => {
        globalThis.studioCalls.loadedProducts = (globalThis.studioCalls.loadedProducts || 0) + 1;
        products.data.loadedAt = new Date().toISOString();
        products.progress = 'Đã tải ' + products.data.rows.length + ' dòng từ Notion';
        return products.snapshot();
      };
      products.scan = async (profileIds, emit) => {
        globalThis.studioCalls.scanned.push(profileIds);
        products.progress = 'Đang quét lại cả hai shop thử nghiệm'; emit();
        await new Promise(resolve => {globalThis.releaseStudioScan = resolve;});
        for (const id of profileIds) {
          const binding = products.data.shops[id], rows = products.data.rows.filter(item => item.profileId === id);
          products.ingest(id, {...binding, shop: binding.name, rows, scannedAt: new Date().toISOString()});
        }
      };
      studio.load = async () => {globalThis.studioCalls.loaded++; return [];};
      gemini.models = async () => ({models: [{id: 'gemini-test-flash', label: 'Gemini Test Flash'}], selected: 'gemini-test-flash', message: 'Danh sách model thử nghiệm'});
      gemini.test = async () => ({message: 'Kết nối thử nghiệm OK'});
      chatgpt.open = async () => ({message: 'Profile thử nghiệm đã mở'}); chatgpt.test = async () => ({message: 'ChatGPT thử nghiệm sẵn sàng'});
      drive.test = () => ({message: 'Thư mục local thử nghiệm ghi được'});
    }, {previewDataUrl, dir});
    await page.reload(); await page.locator('nav [data-tab="replacements"]').click();
    await page.evaluate(async () => renderStudio(await window.srm.call('snapshot')));
    assert.equal(await page.locator('#studio-legacy-source-wrap').isHidden(), true, 'legacy source panel is hidden by default');
    await page.evaluate(() => { const el = document.getElementById('studio-legacy-source-wrap'); if (el) { el.removeAttribute('hidden'); el.open = true; el.style.setProperty('display', 'block', 'important'); } });
    assert.equal(await page.locator('#studio-products input').count(), 2, 'variants collapse to exact product source');
    assert.equal(await page.locator('#studio-products img').count(), 0, 'source names are escaped');
    await page.evaluate(async () => {
      const snapshot = await window.srm.call('snapshot');
      snapshot.products.rows = snapshot.products.rows.filter(item => item.shop === 'shop0');
      renderStudio(snapshot);
    });
    assert.deepEqual(await page.locator('#studio-shop option').evaluateAll(items => items.map(item => item.value)), ['', 'shop0', 'shop1'], 'enabled bound shop remains selectable before its product rows arrive');
    assert.match(await page.locator('#studio-shop option[value="shop0"]').textContent(), /1 sản phẩm/, 'shop labels count products rather than variants');
    assert.match(await page.locator('#studio-source-status').textContent(), /2 shop.*2 profile/, 'source picker explains both shop and profile counts');
    await page.locator('#studio-shop').selectOption('shop1');
    await page.evaluate(async () => {
      const snapshot = await window.srm.call('snapshot');
      snapshot.products.rows = snapshot.products.rows.filter(item => item.shop === 'shop0');
      renderStudio(snapshot);
    });
    assert.equal(await page.locator('#studio-shop').inputValue(), 'shop1', 'snapshot does not reset a bound shop with no product rows');
    assert.match(await page.locator('#studio-products').textContent(), /chưa có sản phẩm/i);
    await page.evaluate(async () => {
      const snapshot = await window.srm.call('snapshot');
      snapshot.products.rows = [];
      snapshot.profiles[1].enabled = false;
      renderStudio(snapshot);
    });
    assert.deepEqual(await page.locator('#studio-shop option').evaluateAll(items => items.map(item => item.value)), ['', 'shop0'], 'an inactive binding with no data is not advertised as an available source');
    await page.evaluate(async () => {
      const snapshot = await window.srm.call('snapshot');
      snapshot.products.rows = []; snapshot.products.shops = {};
      renderStudio(snapshot);
    });
    assert.deepEqual(await page.locator('#studio-shop option').evaluateAll(items => items.map(item => item.value)), [''], 'profile display names never masquerade as verified shop identities');
    assert.equal(await page.locator('#studio-source-scan').isVisible(), true, 'the direct sync button is visible and defaults to Notion products load');
    await page.evaluate(async () => {const snapshot = await window.srm.call('snapshot'); snapshot.scanning = true; renderStudio(snapshot);});
    assert.equal(await page.locator('#studio-source-scan').isDisabled(), true, 'product rescan waits for the returns browser task');
    assert.equal(await page.locator('#studio-load').isDisabled(), true, 'Notion loading follows the same backend task lock');
    assert.match(await page.locator('#studio-source-status').textContent(), /Đang quét hoàn \/ huỷ/);
    await page.evaluate(async () => renderStudio(await window.srm.call('snapshot')));
    await page.locator('#studio-shop').selectOption('');
    assert.equal(await page.locator('#replacement-notion').isHidden(), true, 'secondary Notion actions are tucked into a collapsed menu');
    assert.equal(await page.locator('#studio-load').isHidden(), true);
    await page.locator('#studio-notion-menu summary').click();
    assert.equal(await page.locator('#replacement-notion').isVisible(), true);
    await page.locator('#studio-load').click();
    await page.waitForFunction(() => !document.querySelector('#studio-create').disabled || !document.querySelector('#studio-source-scan').disabled);
    assert.equal(await app.evaluate(() => globalThis.studioCalls.loaded), 1, 'loading saved articles remains accessible via the menu');
    assert.equal(await page.locator('#studio-notion-menu').evaluate(element => element.open), false, 'Notion action closes the compact menu');
    assert.equal(await page.locator('#studio-insights, #studio-insight').count(), 0, 'existing source articles are not multiplied by insight count');
    const library = (await page.evaluate(() => window.srm.call('snapshot'))).studioPrompts;
    assert.equal(library.templates.length, 3, 'three saved starter prompts are available without a selected article');
    const starter = library.templates[0];
    await page.locator('#studio-prompt-template').selectOption(starter.id);
    assert.equal(await page.locator('#studio-prompt-apply').isDisabled(), true, 'a prompt cannot be applied without an editable article');
    await page.locator('#studio-prompt-add').click();
    assert.equal(await page.locator('#studio-prompt-template-name').evaluate(element => document.activeElement === element), true, 'template editor receives keyboard focus');
    await page.locator('#studio-prompt-template-name').press('Escape');
    assert.equal(await page.locator('#studio-prompt-editor').isHidden(), true, 'Escape cancels template editing');
    await page.locator('#studio-prompt-add').click();
    await page.locator('#studio-prompt-template-name').fill('Mẫu <img src=x>');
    await page.locator('#studio-prompt-template-content').fill('Prompt riêng <script>window.hacked=true</script>\nKhông tự chạy AI.');
    await page.evaluate(async () => renderStudio(await window.srm.call('snapshot')));
    assert.equal(await page.locator('#studio-prompt-template-name').inputValue(), 'Mẫu <img src=x>', 'snapshot refresh preserves unsaved template editor');
    await page.locator('#studio-prompt-template-save').click();
    await page.waitForFunction(() => document.querySelector('#studio-prompt-editor').hidden);
    const customId = await page.locator('#studio-prompt-template').inputValue();
    assert.ok(customId);
    assert.equal(await page.locator('#studio-prompt-library img, #studio-prompt-library script').count(), 0, 'template names are escaped');
    assert.equal(await page.locator('#studio-prompt-template').inputValue(), customId, 'the new saved template is selected');
    assert.equal(await app.evaluate(() => globalThis.studioCalls.generated.length), 0, 'managing templates never generates content');
    await page.reload(); await page.locator('nav [data-tab="replacements"]').click();
    await page.evaluate(async () => renderStudio(await window.srm.call('snapshot')));
    await page.evaluate(() => { const el = document.getElementById('studio-legacy-source-wrap'); if (el) { el.removeAttribute('hidden'); el.open = true; el.style.setProperty('display', 'block', 'important'); } });
    await page.locator('#studio-prompt-template').selectOption(customId);
    assert.equal(await page.locator('#studio-prompt-edit').isEnabled(), true, 'saved templates survive renderer reload');
    await page.locator('#studio-shop').selectOption('shop0');
    await page.locator('#studio-products input').first().check();
    await page.waitForFunction(() => document.querySelectorAll('#studio-job option').length === 2).catch(async failure => {failure.message += '\nStudio UI: ' + JSON.stringify({error: await page.locator('#studio-error').textContent(), errors}); throw failure;});
    assert.match(await page.locator('#studio-source').innerText(), /Alpha.*shop0.*ID 123.*Model 456/s);
    assert.equal(await page.locator('#studio-price').inputValue(), '100000');
    assert.equal(await page.locator('#studio-name').inputValue(), 'Alpha <img src=x>', 'the selected existing article name is loaded');
    await page.locator('#studio-prompt').fill('Prompt nhân viên đang nhập.');
    await page.locator('#studio-prompt-template').selectOption(starter.id);
    assert.equal(await page.locator('#studio-prompt').inputValue(), 'Prompt nhân viên đang nhập.', 'selecting a template never silently replaces the draft');
    await page.locator('#studio-prompt-apply').click();
    assert.equal(await page.locator('#studio-prompt').inputValue(), starter.content, 'only explicit Apply fills the article prompt');
    await page.locator('#studio-settings').evaluate(element => { element.hidden = false; element.open = true; });
    await page.locator('#studio-gemini-key').fill('AQ.test-key-not-a-real-secret');
    await page.locator('#studio-prompt-template').selectOption(customId);
    await page.locator('#studio-prompt-edit').click();
    await page.locator('#studio-prompt-template-name').fill('Mẫu đã sửa <img src=x>');
    await page.locator('#studio-prompt-template-content').fill('Nội dung mẫu đã sửa.');
    await page.locator('#studio-prompt-template-save').click();
    await page.waitForFunction(() => document.querySelector('#studio-prompt-editor').hidden);
    assert.equal(await page.locator('#studio-prompt').inputValue(), starter.content, 'editing a library template preserves the active article prompt');
    assert.equal(await page.locator('#studio-name').inputValue(), 'Alpha <img src=x>', 'template CRUD preserves the exact selected product');
    assert.equal(await page.locator('#studio-price').inputValue(), '100000', 'template CRUD preserves the article price');
    assert.equal(await page.locator('#studio-gemini-key').inputValue(), 'AQ.test-key-not-a-real-secret', 'template CRUD preserves an unsaved API key');
    await page.evaluate(async () => renderStudio(await window.srm.call('snapshot')));
    assert.equal(await page.locator('#studio-prompt').inputValue(), starter.content, 'snapshot refresh preserves the unsaved article prompt');
    assert.equal(await page.locator('#studio-gemini-key').inputValue(), 'AQ.test-key-not-a-real-secret', 'snapshot refresh preserves the unsaved key');
    const activeJobId = await page.locator('#studio-job').inputValue();
    await page.locator('#studio-source-scan').click();
    await page.waitForFunction(() => document.querySelector('#studio-source-status').textContent.includes('Đã đồng bộ dữ liệu sản phẩm mới nhất từ Notion'));
    assert.equal(await page.locator('#studio-source-scan').isVisible(), true, 'the direct sync button remains visible');
    assert.equal(await app.evaluate(() => globalThis.studioCalls.loadedProducts >= 1), true, 'source button triggers Notion product load instead of browser scan');
    assert.equal(await app.evaluate(() => globalThis.studioCalls.scanned.length), 0, 'no Shopee profile scan is executed from replacements studio');
    assert.equal(await page.locator('#studio-prompt').inputValue(), starter.content, 'active load preserves the unsaved prompt');
    assert.equal(await page.locator('#studio-gemini-key').inputValue(), 'AQ.test-key-not-a-real-secret', 'active load preserves an unsaved API key');
    assert.equal(await page.locator('#studio-shop').inputValue(), 'shop0', 'rescan preserves the source shop filter');
    assert.equal(await page.locator('#studio-products input:checked').count(), 1, 'rescan preserves selected source rows');
    assert.equal(await page.locator('#studio-job').inputValue(), activeJobId, 'rescan preserves the exact active article');
    assert.equal(await page.locator('#studio-prompt').inputValue(), starter.content, 'completed rescan does not reset a draft');
    assert.equal(await page.locator('#studio-gemini-key').inputValue(), 'AQ.test-key-not-a-real-secret', 'completed rescan does not reset an unsaved key');
    await page.evaluate(async () => {
      const snapshot = await window.srm.call('snapshot');
      snapshot.profiles[0].enabled = false; snapshot.products.rows = snapshot.products.rows.filter(item => item.shop !== 'shop0');
      renderStudio(snapshot);
    });
    assert.equal(await page.locator('#studio-shop').inputValue(), 'shop0', 'current article keeps its exact shop even when its profile is disabled and data is missing');
    assert.equal(await page.locator('#studio-job').inputValue(), activeJobId);
    assert.equal(await page.locator('#studio-prompt').inputValue(), starter.content);
    await page.evaluate(async () => renderStudio(await window.srm.call('snapshot')));
    await page.locator('#studio-products input').first().check();
    await page.waitForFunction(() => !document.querySelector('#studio-create').disabled);
    await page.locator('#studio-gemini-key').fill('');
    await page.locator('#studio-settings').evaluate(element => { element.hidden = true; element.open = false; });
    const customBeforeDelete = (await page.evaluate(() => window.srm.call('snapshot'))).studioPrompts.templates.find(item => item.id === customId);
    assert.equal(customBeforeDelete.name, 'Mẫu đã sửa <img src=x>');
    assert.equal(customBeforeDelete.content, 'Nội dung mẫu đã sửa.');
    await page.evaluate(() => {window.confirm = () => false;});
    await page.locator('#studio-prompt-delete').click();
    assert.equal((await page.evaluate(() => window.srm.call('snapshot'))).studioPrompts.templates.some(item => item.id === customId), true, 'cancelling template deletion preserves it');
    await page.evaluate(() => {window.confirm = () => true;});
    await page.locator('#studio-prompt-delete').click();
    await page.waitForFunction(() => document.querySelector('#studio-prompt-status').textContent.includes('Đã xoá'));
    assert.equal((await page.evaluate(() => window.srm.call('snapshot'))).studioPrompts.templates.some(item => item.id === customId), false);
    assert.equal(await page.locator('#studio-prompt').inputValue(), starter.content, 'deletion preserves applied article drafts');
    assert.equal(await app.evaluate(() => globalThis.studioCalls.generated.length + globalThis.studioCalls.approved.length + globalThis.studioCalls.published.length), 0, 'apply and CRUD do not generate, approve or publish');
    await page.locator('#studio-prompt-template').selectOption(starter.id);
    await page.locator('#studio-prompt-edit').click();
    await page.locator('#studio-prompt-template-name').fill(starter.name + ' · đã chỉnh');
    await page.locator('#studio-prompt-template-save').click();
    await page.waitForFunction(() => document.querySelector('#studio-prompt-editor').hidden);
    await page.locator('#studio-products input').first().uncheck(); await page.locator('#studio-products input').first().check();
    await page.waitForFunction(() => !document.querySelector('#studio-create').disabled);
    assert.equal(await page.locator('#studio-job option').count(), 2, 'reselecting a source reuses its one draft');
    await page.locator('#studio-shop').selectOption(''); await page.locator('#studio-select-visible').click(); await page.locator('#studio-create').click();
    await page.waitForFunction(() => document.querySelectorAll('#studio-job option').length === 3);
    assert.equal(await app.evaluate(() => globalThis.studioCalls.created.every(payload => Object.keys(payload).join() === 'rowIds')), true, 'create IPC carries existing row IDs only');
    assert.equal(await app.evaluate(({app}) => app.srmDriver.studio.data.jobs.length), 2, 'one job per distinct shop/product, including variants');
    assert.equal(await page.locator('#studio-approve').count(), 0, 'the separate approval button is removed');
    assert.equal(await page.locator('#studio-publish').isDisabled(), true);
    await page.locator('#studio-prompt').fill('Viết bám sát nội dung gốc. Không tạo thêm công dụng.');
    await page.locator('#studio-name').fill('Tên mới nhân viên yêu cầu');
    await app.evaluate(({app}) => { app.srmDriver.products.busy = true; });
    await page.evaluate(async () => renderStudio(await window.srm.call('snapshot')));
    assert.equal(await page.locator('#studio-generate').isEnabled(), true, 'Gemini writing remains available during product background activity');
    await app.evaluate(({app}) => { app.srmDriver.products.busy = false; });
    await page.evaluate(async () => renderStudio(await window.srm.call('snapshot')));
    await page.locator('#studio-generate').click(); await page.waitForFunction(() => document.querySelector('#studio-description').value.includes('prompt và tên sản phẩm mới'));
    assert.equal(await app.evaluate(() => globalThis.studioCalls.published.length), 0, 'AI generation never publishes');
    assert.equal(await app.evaluate(() => globalThis.studioCalls.browserReads), 0, 'the real generate IPC never reads a Shopee editor or creates a browser context');
    const generationPayload = await app.evaluate(() => globalThis.studioCalls.generatedRequests.at(-1));
    assert.match(JSON.stringify(generationPayload), /Tên mới nhân viên yêu cầu/, 'the new employee name reaches the Gemini API before writing');
    assert.equal(generationPayload.prompt, 'Viết bám sát nội dung gốc. Không tạo thêm công dụng.');
    assert.equal(generationPayload.requestedName, 'Tên mới nhân viên yêu cầu');
    assert.equal(generationPayload.source, undefined, 'the old source product is only an identity binding, not material for the new article');
    assert.match(await page.locator('#studio-description').inputValue(), /prompt và tên sản phẩm mới/, 'completed API content appears directly in the editable article');
    await page.waitForFunction(() => !document.querySelector('#studio-publish').disabled);
    await page.locator('#studio-name').fill('Tên nhân viên sửa');
    await page.locator('#studio-description').fill('Mô tả đã được nhân viên xem và chỉnh.');
    await page.locator('#studio-price').fill('0');
    assert.equal(await page.locator('#studio-publish').isDisabled(), true, 'invalid prices cannot be sent to Notion');
    await page.locator('#studio-price').fill('125000');
    assert.equal(await page.locator('#studio-publish').isEnabled(), true, 'employee edits publish directly without a second approval action');
    await page.locator('#studio-prompt').fill('Prompt đã đổi sau khi tạo bài.');
    assert.equal(await page.locator('#studio-publish').isDisabled(), true, 'a changed prompt requires regeneration rather than publishing mismatched content');
    await page.locator('#studio-prompt').fill(generationPayload.prompt);
    assert.equal(await page.locator('#studio-publish').isEnabled(), true);
    await app.evaluate(() => { if (typeof globalThis.releaseStudioScan === 'function') globalThis.releaseStudioScan(); });
    await page.waitForFunction(async () => !(await window.srm.call('snapshot')).products.busy);
    await app.evaluate(({app}) => {
      app.srmDriver.scanner.scan = async () => {
        await new Promise(resolve => {globalThis.releaseReturnsScan = resolve;});
        throw Error('Isolated returns scanner completed without live browser evidence');
      };
    });
    const returnProfileId = await app.evaluate(({app}) => app.srmDriver.store.data.profiles[0].id);
    await page.evaluate(id => {window.returnsScanDone = window.srm.call('scan', id).catch(() => {});}, returnProfileId);
    await page.waitForFunction(async () => (await window.srm.call('snapshot')).scanning);
    assert.equal(await page.locator('#studio-publish').isEnabled(), true, 'publish remains available during a real returns scan');
    await page.locator('#studio-publish').click();
    await page.waitForFunction(() => document.querySelector('#studio-step-2').getAttribute('aria-selected') === 'true');
    assert.equal(await app.evaluate(() => globalThis.studioCalls.published.length), 1);
    assert.equal(await app.evaluate(() => globalThis.studioCalls.approved.length), 0, 'publish is the employee confirmation; no approve IPC is invoked');
    assert.equal(await app.evaluate(() => globalThis.studioCalls.browserReads), 0, 'the real publish and read-back guard do not use Shopee');
    assert.equal(await page.evaluate(async () => (await window.srm.call('snapshot')).scanning), true, 'Notion publish never cancels the ongoing returns scan');
    assert.equal(await page.locator('#studio-image-job').inputValue(), activeJobId, 'after publish the same article is selected in the image step');
    assert.equal(await app.evaluate(() => globalThis.studioCalls.images.length), 0, 'opening step 2 does not start ChatGPT automatically');
    const savedArticle = await app.evaluate(({app}) => app.srmDriver.studio.publicJob(app.srmDriver.studio.data.jobs[0]));
    assert.equal(savedArticle.name, 'Tên nhân viên sửa');
    assert.equal(savedArticle.description, 'Mô tả đã được nhân viên xem và chỉnh.');
    assert.equal(savedArticle.price, 125000, 'publish saves the current employee edits before Notion creation');
    assert.equal(savedArticle.contentApproved, true, 'explicit publish retains the downstream image confirmation marker');
    await app.evaluate(() => {globalThis.releaseReturnsScan();});
    await page.waitForFunction(async () => !(await window.srm.call('snapshot')).scanning);
    await page.locator('#studio-step-1').click();
    assert.equal(await page.locator('#studio-name').isEnabled(), true, 'reselecting published draft unlocks fields like a new product');
    assert.equal(await page.locator('#studio-next').isEnabled(), true);
    await page.locator('#studio-next').click();
    assert.match(await page.locator('#studio-source').innerText(), /Beta.*shop1.*ID 124.*Model 457/s);
    assert.equal(await page.locator('#studio-name').inputValue(), 'Beta <img src=x>');
    assert.equal(await page.locator('#studio-price').inputValue(), '210000');
    assert.equal(await page.locator('#studio-publish').isDisabled(), true);
    await page.locator('#studio-step-2').click();
    assert.equal(await page.locator('#studio-images').isDisabled(), true, 'unpublished source article cannot generate images');
    await page.locator('#studio-step-1').click();
    await page.locator('#studio-name').fill('Tên mới của shop phụ');
    await page.locator('#studio-prompt').fill('Viết bài theo tên mới của shop phụ.');
    await page.locator('#studio-generate').click();
    await page.waitForFunction(() => document.querySelector('#studio-name').value === 'Tên mới của shop phụ' && !document.querySelector('#studio-publish').disabled);
    await app.evaluate(() => {globalThis.failAfterNotionCreate = true;});
    await page.locator('#studio-publish').click();
    await page.waitForFunction(() => document.querySelector('#studio-publish').textContent.includes('Đối chiếu') && !document.querySelector('#studio-publish').disabled);
    assert.equal(await page.locator('#studio-step-1').getAttribute('aria-selected'), 'true', 'an uncertain Notion write stays in the article step for reconciliation');
    assert.equal(await page.locator('#studio-name').isDisabled(), true, 'an uncertain write locks the exact sent content');
    assert.equal(await app.evaluate(() => globalThis.studioCalls.notionCreates), 2);
    await page.locator('#studio-publish').click();
    await page.waitForFunction(() => document.querySelector('#studio-step-2').getAttribute('aria-selected') === 'true');
    assert.equal(await app.evaluate(() => globalThis.studioCalls.notionCreates), 2, 'recovery reads the existing Notion article and never creates a duplicate');
    assert.equal(await app.evaluate(() => globalThis.studioCalls.images.length), 0, 'recovery does not automatically create images');
    const publishedId = await app.evaluate(({app}) => app.srmDriver.studio.data.jobs[0].id);
    await app.evaluate(({app}, id) => {app.srmDriver.studio.get(id).baseline = {images: ['https://example.com/image-step-only.jpg']}; app.srmDriver.studio.save();}, publishedId);
    await page.locator('#studio-image-job').selectOption(publishedId);
    assert.equal(await page.locator('#studio-cdp-legacy').isHidden(), true, 'debug controls are no longer exposed in the UI');
    // Exercise the retained legacy handler without making it visible to users.
    await page.locator('#studio-images').evaluate(element => element.click());
    await page.waitForFunction(() => document.querySelectorAll('#studio-gallery figure').length === 5 && !document.querySelector('#studio-go-step3').hidden).catch(async failure => {failure.message += '\nImage step: ' + JSON.stringify({error: await page.locator('#studio-error').textContent(), selected: await page.locator('#studio-image-job').inputValue(), state: await app.evaluate(({app}) => app.srmDriver.studio.data.jobs.map(item => ({id: item.id, status: item.status, notionUrl: item.notionUrl, contentApproved: item.contentApproved, error: item.error}))), calls: await app.evaluate(() => globalThis.studioCalls.images)}); throw failure;});
    assert.equal(await page.locator('#studio-gallery img').count(), 4, 'unsafe image URL is rejected');
    assert.equal(await page.locator('#studio-gallery figcaption img').count(), 0, 'image filename is escaped');
    assert.equal(await app.evaluate(() => globalThis.studioCalls.attached.length), 0, 'images are not attached automatically');
    await page.locator('#studio-go-step3').click();
    await page.waitForFunction(() => !document.querySelector('#studio-attach').disabled);
    await page.locator('#studio-attach').click(); await page.waitForFunction(() => document.querySelector('#studio-ready-status').textContent.includes('Đã có bài và 5 ảnh'));
    assert.equal(await page.locator('#studio-replace').isEnabled(), true);
    await page.locator('#studio-activate').evaluate(element => element.click()); await page.locator('#replacement-preview').waitFor({state: 'visible'});
    assert.equal(await app.evaluate(() => globalThis.studioCalls.activated.length), 1);
    assert.equal(await app.evaluate(() => globalThis.studioCalls.run.length), 0, 'activation only prepares preview, never writes Shopee');
    assert.equal(await page.locator('#studio-error').textContent(), '', 'activation completes without stale references to the removed toolbar');
    assert.equal(await page.evaluate(() => replacementSelection), await app.evaluate(({app}) => app.srmDriver.studio.data.jobs[0].rowId));
    assert.equal(await page.locator('#replacement-product, #replacement-article-form, #replacement-history-rows').count(), 0, 'old duplicate replacement toolbar is removed');
    assert.equal(await page.locator('#replacement-run').isEnabled(), true);
    await page.locator('#studio-settings').evaluate(element => { element.hidden = false; element.open = true; });
    assert.equal(await page.locator('#studio-gemini-key').getAttribute('type'), 'password');
    await page.locator('#studio-models').click(); await page.waitForFunction(() => document.querySelector('#studio-model').value === 'gemini-test-flash');
    assert.equal(await page.locator('#studio-model-list option').count(), 1, 'model list comes from API response');
    await page.locator('#studio-drive-local').fill(dir);await page.locator('#studio-writing-reference').fill('Công dụng\nThành phần\nHướng dẫn'); await page.locator('#studio-config-save').click();
    await page.waitForFunction(() => document.querySelector('#studio-config-status').textContent.includes('Đã lưu'));
    assert.equal((await page.evaluate(()=>window.srm.call('snapshot'))).studioConfig.writingReference,'Công dụng\nThành phần\nHướng dẫn');
    if (process.env.SRM_STUDIO_SCREENSHOT) {
      await page.locator('#studio-settings').evaluate(element => { element.hidden = true; element.open = false; });
      await page.locator('#studio-step-1').click();
      await page.screenshot({path: process.env.SRM_STUDIO_SCREENSHOT, fullPage: true});
    }
    for (const width of [1440, 780, 390]) {
      await app.evaluate(({BrowserWindow}, width) => {const win = BrowserWindow.getAllWindows()[0]; win.setMinimumSize(360, 500); win.setSize(width, 1000);}, width);
      assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'studio fits viewport ' + width);
    }
    assert.deepEqual(errors, []);
    await app.close(); app = null;
    app = await _electron.launch({args: ['.'], cwd: path.resolve(__dirname, '..'), env: {...process.env, SRM_DATA_DIR: dir, SRM_DRIVER: '1'}});
    const reopenedPage = await app.firstWindow(); await reopenedPage.waitForFunction(() => !!window.srm && typeof renderStudio === 'function');
    const afterRestart = (await reopenedPage.evaluate(() => window.srm.call('snapshot'))).studioPrompts;
    assert.equal(afterRestart.templates.find(item => item.id === starter.id).name, starter.name + ' · đã chỉnh', 'edited starter prompt survives app restart');
    assert.equal(afterRestart.templates.some(item => item.id === customId), false, 'deleted templates stay deleted after app restart');
    await reopenedPage.locator('nav [data-tab="replacements"]').click();
    await reopenedPage.evaluate(() => { const el = document.getElementById('studio-legacy-source-wrap'); if (el) { el.removeAttribute('hidden'); el.open = true; el.style.setProperty('display', 'block', 'important'); } });
    await reopenedPage.locator('#studio-shop').selectOption('shop1');
    assert.equal(await reopenedPage.locator('#studio-shop-delete').isEnabled(), true, 'delete button enabled for selected shop');
    await reopenedPage.evaluate(() => { window.confirm = () => true; });
    await reopenedPage.locator('#studio-shop-delete').click();
    await reopenedPage.waitForFunction(() => !document.querySelector('#studio-shop option[value="shop1"]'));
    assert.equal(await reopenedPage.locator('#studio-shop option[value="shop1"]').count(), 0, 'deleted shop is removed from options');
    console.log('PASS Studio UI: all-profile scans, two-shop sources, template CRUD and preserved drafts/keys, real Gemini and Notion IPC during product/returns scans with forbidden Shopee browser reads, employee edits saved on explicit publish without approval, same-article image step without auto-generation, 5 image readiness, safe previews, model/config persistence and responsive layout.');
  } finally {if (app) await app.close(); fs.rmSync(dir, {recursive: true, force: true});}
})().catch(error => {console.error(error); process.exitCode = 1;});
